name: HTML-project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
         html_file: 'index.html'
       
      - name: Checks HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
            root: ./
            log_level: INFO
            css: true
